/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f7fafb",
        "surface-dim": "#d7dadb",
        "surface-bright": "#f7fafb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f5",
        "surface-container": "#ebeeef",
        "surface-container-high": "#e6e9ea",
        "surface-container-highest": "#e0e3e4",
        "on-surface": "#181c1d",
        "on-surface-variant": "#414844",
        "inverse-surface": "#2d3132",
        "inverse-on-surface": "#eef1f2",
        "outline": "#717973",
        "outline-variant": "#c1c8c2",
        "surface-tint": "#3f6653",
        "primary": "#012d1d",
        "on-primary": "#ffffff",
        "primary-container": "#1b4332",
        "on-primary-container": "#86af99",
        "inverse-primary": "#a5d0b9",
        "secondary": "#4c6452",
        "on-secondary": "#ffffff",
        "secondary-container": "#cce6d0",
        "on-secondary-container": "#506856",
        "tertiary": "#002d1b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00452c",
        "on-tertiary-container": "#53b889",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#c1ecd4",
        "primary-fixed-dim": "#a5d0b9",
        "on-primary-fixed": "#002114",
        "on-primary-fixed-variant": "#274e3d",
        "secondary-fixed": "#cee9d3",
        "secondary-fixed-dim": "#b3cdb7",
        "on-secondary-fixed": "#092012",
        "on-secondary-fixed-variant": "#354c3b",
        "tertiary-fixed": "#92f7c3",
        "tertiary-fixed-dim": "#75daa8",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005235",
        "background": "#f7fafb",
        "on-background": "#181c1d",
        "surface-variant": "#e0e3e4",
      },
      fontFamily: {
        "h1": ["Manrope", "sans-serif"],
        "h2": ["Manrope", "sans-serif"],
        "h3": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
      },
      fontSize: {
        "h1": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h2": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h3": ["24px", { lineHeight: "1.4", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        "caption": ["12px", { lineHeight: "1.4", letterSpacing: "0em", fontWeight: "400" }],
      },
      spacing: {
        "unit": "8px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "48px",
        "gutter": "24px",
        "container-max": "1280px"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      }
    },
  },
  plugins: [],
}
